name: bluelink-fastapi-gateway

services:
  api:
    build: .
    container_name: bluelink-api
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "until alembic upgrade head; do
               echo 'Alembic migration failed, retrying in 3 seconds...';
               sleep 3;
             done;
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:16
    container_name: bluelink-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bluelink
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
